@startuml ER

class users {
    + uuid : String(32)
    ---
    name : String(64)
    mail : String(240)
    birth : Data()
    timestamp : Datetime()
}
/'
    全ユーザー
    birth: 誕生日
'/

class client {
    + uuid : String(32)
    ---
    status : Boolen()
    timestamp : Datetime()
}
/'
    クライアント
    status: 有効状態
    false or true
'/

class menta {
    + uuid : String(32)
    ---
    profile : String(1024)
    url : String(124)
    status : Boolen()
    timestamp : Datetime()
}
/'
    メンター

    profile: ポートフォリオ
    url:  youtube url
    status: 有効状態
    
    終了条件をプロフィールに明示する
    完了せずに契約終了した場合返金処理
'/

class review {
    + id : String(32)
    ---
    # menta_id : String(32)
    # client_id : String(32)
    star : Int(1)
    comment : String(1024)
    timestamp : Datetime()
}

class tag {
    + id : String(32)
    ---
    name : String(32)
    timestamp : Datetime()
}
/'
    分野
'/

class client_tag {
    + id : String(32)
    ---
    # client_id : String(32)
    # tag_id : String(32)
    timestamp : Datetime()
}
/'
    clientとタグの関連付け
'/  

class menta_tag {
    + id : String(32)
    ---
    # menta_id : String(32)
    # tag_id : String(32)
    experience : String(32)
    timestamp : Datetime()
}

class like {
    ' 契約前
    + id : String(32)
    ---
    # menta_id : String(32)
    # client_id : String(32)
    status : Bool(1)
    timestamp : Datetime()
}
/'
    契約前
    menta_id: サービス提供者
    client_id: 依頼者
    status: 1で有効0で無効
'/

class contract {
    + id :String(32)
    ---
    # menta_id: String(32)
    # client_id: String(32)
    timestamp : Datetime()
}
/'
    契約済み
'/

class none {
    + id : String(32)
    ---
    # menta_id : String(32)
    # client_id : String(32)
    date : Date()
    timestamp : Datetime()
}
/'
    noneされた人
    一か月表示しない
'/

' class creditcard {
'     # client_id : String(32)
'     number : String(32)
'     name : String(128)
'     limit : String(16)
'     code : String(4)
' }

client - users
users - menta
client --{ like
menta --{ like
contract --{ client
contract --{ menta
none }-- client
none --{ menta
tag --{ client_tag
menta_tag }-- tag
client -{ client_tag
menta --{ menta_tag
client }-- review 
menta --{ review
' creditcard }-- client
@enduml